source: "0"
model: "./models/yolov8n.onnx"
classes: "./models/coco.names"
input_width: 640
input_height: 640
confidence_threshold: 0.35
nms_threshold: 0.45
prefer_cuda: true
alert_unknown_people: false

